spring:
  application:
    name: spring-blog-rest-api


  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: myblog
    password: myblog


  jpa:
    hibernate:
      ddl-auto: update



  banner:
    location: banner

